### ISSUE TITLE
Wi-Fi search not returning results

### ISSUE THREAD

**Issue by SGNTP** [red5coder/jamf-return-to-service#1] opened 2023-10-27 10:45 UTC
Hi Rich,

After entering my test instance details and attempting to search for a Wi-Fi config profiel (I have 2 in my instance) the app doesn't return any results so I can't proceed.  (I'm running Jamf Pro 11 btw).
Is it possible to add a profile manually or refactor for JP11?

**Comment by red5coder** [comment] 2023-10-27 10:51
Hi there

Let me take a look over the weekend and aww what is going on. Will report shorty. Thanks

**Comment by red5coder** [comment] 2023-10-27 15:12
Hi Sanchi

Just tried this with a Jamf Pro 11.0.1 instance.

So far I have been unable to reproduce the issue.

Can. you check the permissions required on the account / role you are using?

The app also should log to "uk.co.mallion.jamf-return-to-service".

Does that show anything?

**Comment by red5coder** [comment] 2023-10-27 16:18
Hi Sanchi

Closing this issue. Cheers

**Closed as completed by red5coder** 2023-10-27 16:18 UTC
